package entity;

public class SvcssStudent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_student.stu_id
     *
     * @mbg.generated
     */
    private String stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_student.stu_name
     *
     * @mbg.generated
     */
    private String stuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_student.stu_gender
     *
     * @mbg.generated
     */
    private String stuGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_student.stu_professional
     *
     * @mbg.generated
     */
    private String stuProfessional;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_student.stu_id
     *
     * @return the value of svcss_student.stu_id
     *
     * @mbg.generated
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_student.stu_id
     *
     * @param stuId the value for svcss_student.stu_id
     *
     * @mbg.generated
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_student.stu_name
     *
     * @return the value of svcss_student.stu_name
     *
     * @mbg.generated
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_student.stu_name
     *
     * @param stuName the value for svcss_student.stu_name
     *
     * @mbg.generated
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_student.stu_gender
     *
     * @return the value of svcss_student.stu_gender
     *
     * @mbg.generated
     */
    public String getStuGender() {
        return stuGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_student.stu_gender
     *
     * @param stuGender the value for svcss_student.stu_gender
     *
     * @mbg.generated
     */
    public void setStuGender(String stuGender) {
        this.stuGender = stuGender == null ? null : stuGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_student.stu_professional
     *
     * @return the value of svcss_student.stu_professional
     *
     * @mbg.generated
     */
    public String getStuProfessional() {
        return stuProfessional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_student.stu_professional
     *
     * @param stuProfessional the value for svcss_student.stu_professional
     *
     * @mbg.generated
     */
    public void setStuProfessional(String stuProfessional) {
        this.stuProfessional = stuProfessional == null ? null : stuProfessional.trim();
    }
}