package entity;

public class SvcssCourseStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_course_status.status_id
     *
     * @mbg.generated
     */
    private String statusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_course_status.status_name
     *
     * @mbg.generated
     */
    private String statusName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_course_status.status_id
     *
     * @return the value of svcss_course_status.status_id
     *
     * @mbg.generated
     */
    public String getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_course_status.status_id
     *
     * @param statusId the value for svcss_course_status.status_id
     *
     * @mbg.generated
     */
    public void setStatusId(String statusId) {
        this.statusId = statusId == null ? null : statusId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_course_status.status_name
     *
     * @return the value of svcss_course_status.status_name
     *
     * @mbg.generated
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_course_status.status_name
     *
     * @param statusName the value for svcss_course_status.status_name
     *
     * @mbg.generated
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName == null ? null : statusName.trim();
    }
}