package entity;

import java.util.ArrayList;
import java.util.List;

public class SvcssGateNumberExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table svcss_gate_number
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table svcss_gate_number
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table svcss_gate_number
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_gate_number
     *
     * @mbg.generated
     */
    public SvcssGateNumberExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_gate_number
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_gate_number
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_gate_number
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_gate_number
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_gate_number
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_gate_number
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_gate_number
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_gate_number
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_gate_number
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_gate_number
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table svcss_gate_number
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStuProfessionalIsNull() {
            addCriterion("stu_professional is null");
            return (Criteria) this;
        }

        public Criteria andStuProfessionalIsNotNull() {
            addCriterion("stu_professional is not null");
            return (Criteria) this;
        }

        public Criteria andStuProfessionalEqualTo(String value) {
            addCriterion("stu_professional =", value, "stuProfessional");
            return (Criteria) this;
        }

        public Criteria andStuProfessionalNotEqualTo(String value) {
            addCriterion("stu_professional <>", value, "stuProfessional");
            return (Criteria) this;
        }

        public Criteria andStuProfessionalGreaterThan(String value) {
            addCriterion("stu_professional >", value, "stuProfessional");
            return (Criteria) this;
        }

        public Criteria andStuProfessionalGreaterThanOrEqualTo(String value) {
            addCriterion("stu_professional >=", value, "stuProfessional");
            return (Criteria) this;
        }

        public Criteria andStuProfessionalLessThan(String value) {
            addCriterion("stu_professional <", value, "stuProfessional");
            return (Criteria) this;
        }

        public Criteria andStuProfessionalLessThanOrEqualTo(String value) {
            addCriterion("stu_professional <=", value, "stuProfessional");
            return (Criteria) this;
        }

        public Criteria andStuProfessionalLike(String value) {
            addCriterion("stu_professional like", value, "stuProfessional");
            return (Criteria) this;
        }

        public Criteria andStuProfessionalNotLike(String value) {
            addCriterion("stu_professional not like", value, "stuProfessional");
            return (Criteria) this;
        }

        public Criteria andStuProfessionalIn(List<String> values) {
            addCriterion("stu_professional in", values, "stuProfessional");
            return (Criteria) this;
        }

        public Criteria andStuProfessionalNotIn(List<String> values) {
            addCriterion("stu_professional not in", values, "stuProfessional");
            return (Criteria) this;
        }

        public Criteria andStuProfessionalBetween(String value1, String value2) {
            addCriterion("stu_professional between", value1, value2, "stuProfessional");
            return (Criteria) this;
        }

        public Criteria andStuProfessionalNotBetween(String value1, String value2) {
            addCriterion("stu_professional not between", value1, value2, "stuProfessional");
            return (Criteria) this;
        }

        public Criteria andCourseGateNumberIsNull() {
            addCriterion("course_gate_number is null");
            return (Criteria) this;
        }

        public Criteria andCourseGateNumberIsNotNull() {
            addCriterion("course_gate_number is not null");
            return (Criteria) this;
        }

        public Criteria andCourseGateNumberEqualTo(Integer value) {
            addCriterion("course_gate_number =", value, "courseGateNumber");
            return (Criteria) this;
        }

        public Criteria andCourseGateNumberNotEqualTo(Integer value) {
            addCriterion("course_gate_number <>", value, "courseGateNumber");
            return (Criteria) this;
        }

        public Criteria andCourseGateNumberGreaterThan(Integer value) {
            addCriterion("course_gate_number >", value, "courseGateNumber");
            return (Criteria) this;
        }

        public Criteria andCourseGateNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("course_gate_number >=", value, "courseGateNumber");
            return (Criteria) this;
        }

        public Criteria andCourseGateNumberLessThan(Integer value) {
            addCriterion("course_gate_number <", value, "courseGateNumber");
            return (Criteria) this;
        }

        public Criteria andCourseGateNumberLessThanOrEqualTo(Integer value) {
            addCriterion("course_gate_number <=", value, "courseGateNumber");
            return (Criteria) this;
        }

        public Criteria andCourseGateNumberIn(List<Integer> values) {
            addCriterion("course_gate_number in", values, "courseGateNumber");
            return (Criteria) this;
        }

        public Criteria andCourseGateNumberNotIn(List<Integer> values) {
            addCriterion("course_gate_number not in", values, "courseGateNumber");
            return (Criteria) this;
        }

        public Criteria andCourseGateNumberBetween(Integer value1, Integer value2) {
            addCriterion("course_gate_number between", value1, value2, "courseGateNumber");
            return (Criteria) this;
        }

        public Criteria andCourseGateNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("course_gate_number not between", value1, value2, "courseGateNumber");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table svcss_gate_number
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table svcss_gate_number
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}