package entity;

public class SvcssGrade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_grade.grade_id
     *
     * @mbg.generated
     */
    private String gradeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_grade.grade_course_id
     *
     * @mbg.generated
     */
    private String gradeCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_grade.grade_stu_id
     *
     * @mbg.generated
     */
    private String gradeStuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_grade.grade_teachers_comments
     *
     * @mbg.generated
     */
    private String gradeTeachersComments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_grade.grade_regular_score
     *
     * @mbg.generated
     */
    private String gradeRegularScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_grade.grade_final_score
     *
     * @mbg.generated
     */
    private String gradeFinalScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_grade.grade_total_score
     *
     * @mbg.generated
     */
    private String gradeTotalScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_grade.grade_is_grade
     *
     * @mbg.generated
     */
    private String gradeIsGrade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_grade.grade_id
     *
     * @return the value of svcss_grade.grade_id
     *
     * @mbg.generated
     */
    public String getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_grade.grade_id
     *
     * @param gradeId the value for svcss_grade.grade_id
     *
     * @mbg.generated
     */
    public void setGradeId(String gradeId) {
        this.gradeId = gradeId == null ? null : gradeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_grade.grade_course_id
     *
     * @return the value of svcss_grade.grade_course_id
     *
     * @mbg.generated
     */
    public String getGradeCourseId() {
        return gradeCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_grade.grade_course_id
     *
     * @param gradeCourseId the value for svcss_grade.grade_course_id
     *
     * @mbg.generated
     */
    public void setGradeCourseId(String gradeCourseId) {
        this.gradeCourseId = gradeCourseId == null ? null : gradeCourseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_grade.grade_stu_id
     *
     * @return the value of svcss_grade.grade_stu_id
     *
     * @mbg.generated
     */
    public String getGradeStuId() {
        return gradeStuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_grade.grade_stu_id
     *
     * @param gradeStuId the value for svcss_grade.grade_stu_id
     *
     * @mbg.generated
     */
    public void setGradeStuId(String gradeStuId) {
        this.gradeStuId = gradeStuId == null ? null : gradeStuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_grade.grade_teachers_comments
     *
     * @return the value of svcss_grade.grade_teachers_comments
     *
     * @mbg.generated
     */
    public String getGradeTeachersComments() {
        return gradeTeachersComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_grade.grade_teachers_comments
     *
     * @param gradeTeachersComments the value for svcss_grade.grade_teachers_comments
     *
     * @mbg.generated
     */
    public void setGradeTeachersComments(String gradeTeachersComments) {
        this.gradeTeachersComments = gradeTeachersComments == null ? null : gradeTeachersComments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_grade.grade_regular_score
     *
     * @return the value of svcss_grade.grade_regular_score
     *
     * @mbg.generated
     */
    public String getGradeRegularScore() {
        return gradeRegularScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_grade.grade_regular_score
     *
     * @param gradeRegularScore the value for svcss_grade.grade_regular_score
     *
     * @mbg.generated
     */
    public void setGradeRegularScore(String gradeRegularScore) {
        this.gradeRegularScore = gradeRegularScore == null ? null : gradeRegularScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_grade.grade_final_score
     *
     * @return the value of svcss_grade.grade_final_score
     *
     * @mbg.generated
     */
    public String getGradeFinalScore() {
        return gradeFinalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_grade.grade_final_score
     *
     * @param gradeFinalScore the value for svcss_grade.grade_final_score
     *
     * @mbg.generated
     */
    public void setGradeFinalScore(String gradeFinalScore) {
        this.gradeFinalScore = gradeFinalScore == null ? null : gradeFinalScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_grade.grade_total_score
     *
     * @return the value of svcss_grade.grade_total_score
     *
     * @mbg.generated
     */
    public String getGradeTotalScore() {
        return gradeTotalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_grade.grade_total_score
     *
     * @param gradeTotalScore the value for svcss_grade.grade_total_score
     *
     * @mbg.generated
     */
    public void setGradeTotalScore(String gradeTotalScore) {
        this.gradeTotalScore = gradeTotalScore == null ? null : gradeTotalScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_grade.grade_is_grade
     *
     * @return the value of svcss_grade.grade_is_grade
     *
     * @mbg.generated
     */
    public String getGradeIsGrade() {
        return gradeIsGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_grade.grade_is_grade
     *
     * @param gradeIsGrade the value for svcss_grade.grade_is_grade
     *
     * @mbg.generated
     */
    public void setGradeIsGrade(String gradeIsGrade) {
        this.gradeIsGrade = gradeIsGrade == null ? null : gradeIsGrade.trim();
    }
}