package entity;

public class SvcssManager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_manager.manager_id
     *
     * @mbg.generated
     */
    private String managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_manager.manager_name
     *
     * @mbg.generated
     */
    private String managerName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_manager.manager_id
     *
     * @return the value of svcss_manager.manager_id
     *
     * @mbg.generated
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_manager.manager_id
     *
     * @param managerId the value for svcss_manager.manager_id
     *
     * @mbg.generated
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId == null ? null : managerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_manager.manager_name
     *
     * @return the value of svcss_manager.manager_name
     *
     * @mbg.generated
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_manager.manager_name
     *
     * @param managerName the value for svcss_manager.manager_name
     *
     * @mbg.generated
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }
}