package entity;

import java.util.Date;

public class SvcssTimeChoose {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_time_choose.course_start_choose
     *
     * @mbg.generated
     */
    private Date courseStartChoose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_time_choose.course_end_choose
     *
     * @mbg.generated
     */
    private Date courseEndChoose;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_time_choose.course_start_choose
     *
     * @return the value of svcss_time_choose.course_start_choose
     *
     * @mbg.generated
     */
    public Date getCourseStartChoose() {
        return courseStartChoose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_time_choose.course_start_choose
     *
     * @param courseStartChoose the value for svcss_time_choose.course_start_choose
     *
     * @mbg.generated
     */
    public void setCourseStartChoose(Date courseStartChoose) {
        this.courseStartChoose = courseStartChoose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_time_choose.course_end_choose
     *
     * @return the value of svcss_time_choose.course_end_choose
     *
     * @mbg.generated
     */
    public Date getCourseEndChoose() {
        return courseEndChoose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_time_choose.course_end_choose
     *
     * @param courseEndChoose the value for svcss_time_choose.course_end_choose
     *
     * @mbg.generated
     */
    public void setCourseEndChoose(Date courseEndChoose) {
        this.courseEndChoose = courseEndChoose;
    }
}