package entity;

public class SvcssCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_course.course_id
     *
     * @mbg.generated
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_course.course_capacity
     *
     * @mbg.generated
     */
    private String courseCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_course.course_residual capacity
     *
     * @mbg.generated
     */
    private String courseResidualCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_course.course_schooltime
     *
     * @mbg.generated
     */
    private String courseSchooltime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_course.coures_class_location
     *
     * @mbg.generated
     */
    private String couresClassLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_course.coures_company_id
     *
     * @mbg.generated
     */
    private String couresCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_course.course_teacher_id
     *
     * @mbg.generated
     */
    private String courseTeacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_course.course_status_id
     *
     * @mbg.generated
     */
    private String courseStatusId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_course.course_id
     *
     * @return the value of svcss_course.course_id
     *
     * @mbg.generated
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_course.course_id
     *
     * @param courseId the value for svcss_course.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_course.course_capacity
     *
     * @return the value of svcss_course.course_capacity
     *
     * @mbg.generated
     */
    public String getCourseCapacity() {
        return courseCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_course.course_capacity
     *
     * @param courseCapacity the value for svcss_course.course_capacity
     *
     * @mbg.generated
     */
    public void setCourseCapacity(String courseCapacity) {
        this.courseCapacity = courseCapacity == null ? null : courseCapacity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_course.course_residual capacity
     *
     * @return the value of svcss_course.course_residual capacity
     *
     * @mbg.generated
     */
    public String getCourseResidualCapacity() {
        return courseResidualCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_course.course_residual capacity
     *
     * @param courseResidualCapacity the value for svcss_course.course_residual capacity
     *
     * @mbg.generated
     */
    public void setCourseResidualCapacity(String courseResidualCapacity) {
        this.courseResidualCapacity = courseResidualCapacity == null ? null : courseResidualCapacity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_course.course_schooltime
     *
     * @return the value of svcss_course.course_schooltime
     *
     * @mbg.generated
     */
    public String getCourseSchooltime() {
        return courseSchooltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_course.course_schooltime
     *
     * @param courseSchooltime the value for svcss_course.course_schooltime
     *
     * @mbg.generated
     */
    public void setCourseSchooltime(String courseSchooltime) {
        this.courseSchooltime = courseSchooltime == null ? null : courseSchooltime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_course.coures_class_location
     *
     * @return the value of svcss_course.coures_class_location
     *
     * @mbg.generated
     */
    public String getCouresClassLocation() {
        return couresClassLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_course.coures_class_location
     *
     * @param couresClassLocation the value for svcss_course.coures_class_location
     *
     * @mbg.generated
     */
    public void setCouresClassLocation(String couresClassLocation) {
        this.couresClassLocation = couresClassLocation == null ? null : couresClassLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_course.coures_company_id
     *
     * @return the value of svcss_course.coures_company_id
     *
     * @mbg.generated
     */
    public String getCouresCompanyId() {
        return couresCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_course.coures_company_id
     *
     * @param couresCompanyId the value for svcss_course.coures_company_id
     *
     * @mbg.generated
     */
    public void setCouresCompanyId(String couresCompanyId) {
        this.couresCompanyId = couresCompanyId == null ? null : couresCompanyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_course.course_teacher_id
     *
     * @return the value of svcss_course.course_teacher_id
     *
     * @mbg.generated
     */
    public String getCourseTeacherId() {
        return courseTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_course.course_teacher_id
     *
     * @param courseTeacherId the value for svcss_course.course_teacher_id
     *
     * @mbg.generated
     */
    public void setCourseTeacherId(String courseTeacherId) {
        this.courseTeacherId = courseTeacherId == null ? null : courseTeacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_course.course_status_id
     *
     * @return the value of svcss_course.course_status_id
     *
     * @mbg.generated
     */
    public String getCourseStatusId() {
        return courseStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_course.course_status_id
     *
     * @param courseStatusId the value for svcss_course.course_status_id
     *
     * @mbg.generated
     */
    public void setCourseStatusId(String courseStatusId) {
        this.courseStatusId = courseStatusId == null ? null : courseStatusId.trim();
    }
}