package entity;

import java.util.ArrayList;
import java.util.List;

public class SvcssGradeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    public SvcssGradeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGradeIdIsNull() {
            addCriterion("grade_id is null");
            return (Criteria) this;
        }

        public Criteria andGradeIdIsNotNull() {
            addCriterion("grade_id is not null");
            return (Criteria) this;
        }

        public Criteria andGradeIdEqualTo(String value) {
            addCriterion("grade_id =", value, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdNotEqualTo(String value) {
            addCriterion("grade_id <>", value, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdGreaterThan(String value) {
            addCriterion("grade_id >", value, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdGreaterThanOrEqualTo(String value) {
            addCriterion("grade_id >=", value, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdLessThan(String value) {
            addCriterion("grade_id <", value, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdLessThanOrEqualTo(String value) {
            addCriterion("grade_id <=", value, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdLike(String value) {
            addCriterion("grade_id like", value, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdNotLike(String value) {
            addCriterion("grade_id not like", value, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdIn(List<String> values) {
            addCriterion("grade_id in", values, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdNotIn(List<String> values) {
            addCriterion("grade_id not in", values, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdBetween(String value1, String value2) {
            addCriterion("grade_id between", value1, value2, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeIdNotBetween(String value1, String value2) {
            addCriterion("grade_id not between", value1, value2, "gradeId");
            return (Criteria) this;
        }

        public Criteria andGradeCourseIdIsNull() {
            addCriterion("grade_course_id is null");
            return (Criteria) this;
        }

        public Criteria andGradeCourseIdIsNotNull() {
            addCriterion("grade_course_id is not null");
            return (Criteria) this;
        }

        public Criteria andGradeCourseIdEqualTo(String value) {
            addCriterion("grade_course_id =", value, "gradeCourseId");
            return (Criteria) this;
        }

        public Criteria andGradeCourseIdNotEqualTo(String value) {
            addCriterion("grade_course_id <>", value, "gradeCourseId");
            return (Criteria) this;
        }

        public Criteria andGradeCourseIdGreaterThan(String value) {
            addCriterion("grade_course_id >", value, "gradeCourseId");
            return (Criteria) this;
        }

        public Criteria andGradeCourseIdGreaterThanOrEqualTo(String value) {
            addCriterion("grade_course_id >=", value, "gradeCourseId");
            return (Criteria) this;
        }

        public Criteria andGradeCourseIdLessThan(String value) {
            addCriterion("grade_course_id <", value, "gradeCourseId");
            return (Criteria) this;
        }

        public Criteria andGradeCourseIdLessThanOrEqualTo(String value) {
            addCriterion("grade_course_id <=", value, "gradeCourseId");
            return (Criteria) this;
        }

        public Criteria andGradeCourseIdLike(String value) {
            addCriterion("grade_course_id like", value, "gradeCourseId");
            return (Criteria) this;
        }

        public Criteria andGradeCourseIdNotLike(String value) {
            addCriterion("grade_course_id not like", value, "gradeCourseId");
            return (Criteria) this;
        }

        public Criteria andGradeCourseIdIn(List<String> values) {
            addCriterion("grade_course_id in", values, "gradeCourseId");
            return (Criteria) this;
        }

        public Criteria andGradeCourseIdNotIn(List<String> values) {
            addCriterion("grade_course_id not in", values, "gradeCourseId");
            return (Criteria) this;
        }

        public Criteria andGradeCourseIdBetween(String value1, String value2) {
            addCriterion("grade_course_id between", value1, value2, "gradeCourseId");
            return (Criteria) this;
        }

        public Criteria andGradeCourseIdNotBetween(String value1, String value2) {
            addCriterion("grade_course_id not between", value1, value2, "gradeCourseId");
            return (Criteria) this;
        }

        public Criteria andGradeStuIdIsNull() {
            addCriterion("grade_stu_id is null");
            return (Criteria) this;
        }

        public Criteria andGradeStuIdIsNotNull() {
            addCriterion("grade_stu_id is not null");
            return (Criteria) this;
        }

        public Criteria andGradeStuIdEqualTo(String value) {
            addCriterion("grade_stu_id =", value, "gradeStuId");
            return (Criteria) this;
        }

        public Criteria andGradeStuIdNotEqualTo(String value) {
            addCriterion("grade_stu_id <>", value, "gradeStuId");
            return (Criteria) this;
        }

        public Criteria andGradeStuIdGreaterThan(String value) {
            addCriterion("grade_stu_id >", value, "gradeStuId");
            return (Criteria) this;
        }

        public Criteria andGradeStuIdGreaterThanOrEqualTo(String value) {
            addCriterion("grade_stu_id >=", value, "gradeStuId");
            return (Criteria) this;
        }

        public Criteria andGradeStuIdLessThan(String value) {
            addCriterion("grade_stu_id <", value, "gradeStuId");
            return (Criteria) this;
        }

        public Criteria andGradeStuIdLessThanOrEqualTo(String value) {
            addCriterion("grade_stu_id <=", value, "gradeStuId");
            return (Criteria) this;
        }

        public Criteria andGradeStuIdLike(String value) {
            addCriterion("grade_stu_id like", value, "gradeStuId");
            return (Criteria) this;
        }

        public Criteria andGradeStuIdNotLike(String value) {
            addCriterion("grade_stu_id not like", value, "gradeStuId");
            return (Criteria) this;
        }

        public Criteria andGradeStuIdIn(List<String> values) {
            addCriterion("grade_stu_id in", values, "gradeStuId");
            return (Criteria) this;
        }

        public Criteria andGradeStuIdNotIn(List<String> values) {
            addCriterion("grade_stu_id not in", values, "gradeStuId");
            return (Criteria) this;
        }

        public Criteria andGradeStuIdBetween(String value1, String value2) {
            addCriterion("grade_stu_id between", value1, value2, "gradeStuId");
            return (Criteria) this;
        }

        public Criteria andGradeStuIdNotBetween(String value1, String value2) {
            addCriterion("grade_stu_id not between", value1, value2, "gradeStuId");
            return (Criteria) this;
        }

        public Criteria andGradeTeachersCommentsIsNull() {
            addCriterion("grade_teachers_comments is null");
            return (Criteria) this;
        }

        public Criteria andGradeTeachersCommentsIsNotNull() {
            addCriterion("grade_teachers_comments is not null");
            return (Criteria) this;
        }

        public Criteria andGradeTeachersCommentsEqualTo(String value) {
            addCriterion("grade_teachers_comments =", value, "gradeTeachersComments");
            return (Criteria) this;
        }

        public Criteria andGradeTeachersCommentsNotEqualTo(String value) {
            addCriterion("grade_teachers_comments <>", value, "gradeTeachersComments");
            return (Criteria) this;
        }

        public Criteria andGradeTeachersCommentsGreaterThan(String value) {
            addCriterion("grade_teachers_comments >", value, "gradeTeachersComments");
            return (Criteria) this;
        }

        public Criteria andGradeTeachersCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("grade_teachers_comments >=", value, "gradeTeachersComments");
            return (Criteria) this;
        }

        public Criteria andGradeTeachersCommentsLessThan(String value) {
            addCriterion("grade_teachers_comments <", value, "gradeTeachersComments");
            return (Criteria) this;
        }

        public Criteria andGradeTeachersCommentsLessThanOrEqualTo(String value) {
            addCriterion("grade_teachers_comments <=", value, "gradeTeachersComments");
            return (Criteria) this;
        }

        public Criteria andGradeTeachersCommentsLike(String value) {
            addCriterion("grade_teachers_comments like", value, "gradeTeachersComments");
            return (Criteria) this;
        }

        public Criteria andGradeTeachersCommentsNotLike(String value) {
            addCriterion("grade_teachers_comments not like", value, "gradeTeachersComments");
            return (Criteria) this;
        }

        public Criteria andGradeTeachersCommentsIn(List<String> values) {
            addCriterion("grade_teachers_comments in", values, "gradeTeachersComments");
            return (Criteria) this;
        }

        public Criteria andGradeTeachersCommentsNotIn(List<String> values) {
            addCriterion("grade_teachers_comments not in", values, "gradeTeachersComments");
            return (Criteria) this;
        }

        public Criteria andGradeTeachersCommentsBetween(String value1, String value2) {
            addCriterion("grade_teachers_comments between", value1, value2, "gradeTeachersComments");
            return (Criteria) this;
        }

        public Criteria andGradeTeachersCommentsNotBetween(String value1, String value2) {
            addCriterion("grade_teachers_comments not between", value1, value2, "gradeTeachersComments");
            return (Criteria) this;
        }

        public Criteria andGradeRegularScoreIsNull() {
            addCriterion("grade_regular_score is null");
            return (Criteria) this;
        }

        public Criteria andGradeRegularScoreIsNotNull() {
            addCriterion("grade_regular_score is not null");
            return (Criteria) this;
        }

        public Criteria andGradeRegularScoreEqualTo(String value) {
            addCriterion("grade_regular_score =", value, "gradeRegularScore");
            return (Criteria) this;
        }

        public Criteria andGradeRegularScoreNotEqualTo(String value) {
            addCriterion("grade_regular_score <>", value, "gradeRegularScore");
            return (Criteria) this;
        }

        public Criteria andGradeRegularScoreGreaterThan(String value) {
            addCriterion("grade_regular_score >", value, "gradeRegularScore");
            return (Criteria) this;
        }

        public Criteria andGradeRegularScoreGreaterThanOrEqualTo(String value) {
            addCriterion("grade_regular_score >=", value, "gradeRegularScore");
            return (Criteria) this;
        }

        public Criteria andGradeRegularScoreLessThan(String value) {
            addCriterion("grade_regular_score <", value, "gradeRegularScore");
            return (Criteria) this;
        }

        public Criteria andGradeRegularScoreLessThanOrEqualTo(String value) {
            addCriterion("grade_regular_score <=", value, "gradeRegularScore");
            return (Criteria) this;
        }

        public Criteria andGradeRegularScoreLike(String value) {
            addCriterion("grade_regular_score like", value, "gradeRegularScore");
            return (Criteria) this;
        }

        public Criteria andGradeRegularScoreNotLike(String value) {
            addCriterion("grade_regular_score not like", value, "gradeRegularScore");
            return (Criteria) this;
        }

        public Criteria andGradeRegularScoreIn(List<String> values) {
            addCriterion("grade_regular_score in", values, "gradeRegularScore");
            return (Criteria) this;
        }

        public Criteria andGradeRegularScoreNotIn(List<String> values) {
            addCriterion("grade_regular_score not in", values, "gradeRegularScore");
            return (Criteria) this;
        }

        public Criteria andGradeRegularScoreBetween(String value1, String value2) {
            addCriterion("grade_regular_score between", value1, value2, "gradeRegularScore");
            return (Criteria) this;
        }

        public Criteria andGradeRegularScoreNotBetween(String value1, String value2) {
            addCriterion("grade_regular_score not between", value1, value2, "gradeRegularScore");
            return (Criteria) this;
        }

        public Criteria andGradeFinalScoreIsNull() {
            addCriterion("grade_final_score is null");
            return (Criteria) this;
        }

        public Criteria andGradeFinalScoreIsNotNull() {
            addCriterion("grade_final_score is not null");
            return (Criteria) this;
        }

        public Criteria andGradeFinalScoreEqualTo(String value) {
            addCriterion("grade_final_score =", value, "gradeFinalScore");
            return (Criteria) this;
        }

        public Criteria andGradeFinalScoreNotEqualTo(String value) {
            addCriterion("grade_final_score <>", value, "gradeFinalScore");
            return (Criteria) this;
        }

        public Criteria andGradeFinalScoreGreaterThan(String value) {
            addCriterion("grade_final_score >", value, "gradeFinalScore");
            return (Criteria) this;
        }

        public Criteria andGradeFinalScoreGreaterThanOrEqualTo(String value) {
            addCriterion("grade_final_score >=", value, "gradeFinalScore");
            return (Criteria) this;
        }

        public Criteria andGradeFinalScoreLessThan(String value) {
            addCriterion("grade_final_score <", value, "gradeFinalScore");
            return (Criteria) this;
        }

        public Criteria andGradeFinalScoreLessThanOrEqualTo(String value) {
            addCriterion("grade_final_score <=", value, "gradeFinalScore");
            return (Criteria) this;
        }

        public Criteria andGradeFinalScoreLike(String value) {
            addCriterion("grade_final_score like", value, "gradeFinalScore");
            return (Criteria) this;
        }

        public Criteria andGradeFinalScoreNotLike(String value) {
            addCriterion("grade_final_score not like", value, "gradeFinalScore");
            return (Criteria) this;
        }

        public Criteria andGradeFinalScoreIn(List<String> values) {
            addCriterion("grade_final_score in", values, "gradeFinalScore");
            return (Criteria) this;
        }

        public Criteria andGradeFinalScoreNotIn(List<String> values) {
            addCriterion("grade_final_score not in", values, "gradeFinalScore");
            return (Criteria) this;
        }

        public Criteria andGradeFinalScoreBetween(String value1, String value2) {
            addCriterion("grade_final_score between", value1, value2, "gradeFinalScore");
            return (Criteria) this;
        }

        public Criteria andGradeFinalScoreNotBetween(String value1, String value2) {
            addCriterion("grade_final_score not between", value1, value2, "gradeFinalScore");
            return (Criteria) this;
        }

        public Criteria andGradeTotalScoreIsNull() {
            addCriterion("grade_total_score is null");
            return (Criteria) this;
        }

        public Criteria andGradeTotalScoreIsNotNull() {
            addCriterion("grade_total_score is not null");
            return (Criteria) this;
        }

        public Criteria andGradeTotalScoreEqualTo(String value) {
            addCriterion("grade_total_score =", value, "gradeTotalScore");
            return (Criteria) this;
        }

        public Criteria andGradeTotalScoreNotEqualTo(String value) {
            addCriterion("grade_total_score <>", value, "gradeTotalScore");
            return (Criteria) this;
        }

        public Criteria andGradeTotalScoreGreaterThan(String value) {
            addCriterion("grade_total_score >", value, "gradeTotalScore");
            return (Criteria) this;
        }

        public Criteria andGradeTotalScoreGreaterThanOrEqualTo(String value) {
            addCriterion("grade_total_score >=", value, "gradeTotalScore");
            return (Criteria) this;
        }

        public Criteria andGradeTotalScoreLessThan(String value) {
            addCriterion("grade_total_score <", value, "gradeTotalScore");
            return (Criteria) this;
        }

        public Criteria andGradeTotalScoreLessThanOrEqualTo(String value) {
            addCriterion("grade_total_score <=", value, "gradeTotalScore");
            return (Criteria) this;
        }

        public Criteria andGradeTotalScoreLike(String value) {
            addCriterion("grade_total_score like", value, "gradeTotalScore");
            return (Criteria) this;
        }

        public Criteria andGradeTotalScoreNotLike(String value) {
            addCriterion("grade_total_score not like", value, "gradeTotalScore");
            return (Criteria) this;
        }

        public Criteria andGradeTotalScoreIn(List<String> values) {
            addCriterion("grade_total_score in", values, "gradeTotalScore");
            return (Criteria) this;
        }

        public Criteria andGradeTotalScoreNotIn(List<String> values) {
            addCriterion("grade_total_score not in", values, "gradeTotalScore");
            return (Criteria) this;
        }

        public Criteria andGradeTotalScoreBetween(String value1, String value2) {
            addCriterion("grade_total_score between", value1, value2, "gradeTotalScore");
            return (Criteria) this;
        }

        public Criteria andGradeTotalScoreNotBetween(String value1, String value2) {
            addCriterion("grade_total_score not between", value1, value2, "gradeTotalScore");
            return (Criteria) this;
        }

        public Criteria andGradeIsGradeIsNull() {
            addCriterion("grade_is_grade is null");
            return (Criteria) this;
        }

        public Criteria andGradeIsGradeIsNotNull() {
            addCriterion("grade_is_grade is not null");
            return (Criteria) this;
        }

        public Criteria andGradeIsGradeEqualTo(String value) {
            addCriterion("grade_is_grade =", value, "gradeIsGrade");
            return (Criteria) this;
        }

        public Criteria andGradeIsGradeNotEqualTo(String value) {
            addCriterion("grade_is_grade <>", value, "gradeIsGrade");
            return (Criteria) this;
        }

        public Criteria andGradeIsGradeGreaterThan(String value) {
            addCriterion("grade_is_grade >", value, "gradeIsGrade");
            return (Criteria) this;
        }

        public Criteria andGradeIsGradeGreaterThanOrEqualTo(String value) {
            addCriterion("grade_is_grade >=", value, "gradeIsGrade");
            return (Criteria) this;
        }

        public Criteria andGradeIsGradeLessThan(String value) {
            addCriterion("grade_is_grade <", value, "gradeIsGrade");
            return (Criteria) this;
        }

        public Criteria andGradeIsGradeLessThanOrEqualTo(String value) {
            addCriterion("grade_is_grade <=", value, "gradeIsGrade");
            return (Criteria) this;
        }

        public Criteria andGradeIsGradeLike(String value) {
            addCriterion("grade_is_grade like", value, "gradeIsGrade");
            return (Criteria) this;
        }

        public Criteria andGradeIsGradeNotLike(String value) {
            addCriterion("grade_is_grade not like", value, "gradeIsGrade");
            return (Criteria) this;
        }

        public Criteria andGradeIsGradeIn(List<String> values) {
            addCriterion("grade_is_grade in", values, "gradeIsGrade");
            return (Criteria) this;
        }

        public Criteria andGradeIsGradeNotIn(List<String> values) {
            addCriterion("grade_is_grade not in", values, "gradeIsGrade");
            return (Criteria) this;
        }

        public Criteria andGradeIsGradeBetween(String value1, String value2) {
            addCriterion("grade_is_grade between", value1, value2, "gradeIsGrade");
            return (Criteria) this;
        }

        public Criteria andGradeIsGradeNotBetween(String value1, String value2) {
            addCriterion("grade_is_grade not between", value1, value2, "gradeIsGrade");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table svcss_grade
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}