package entity;

public class SvcssInvitationCode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_invitation_code.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_invitation_code.code
     *
     * @return the value of svcss_invitation_code.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_invitation_code.code
     *
     * @param code the value for svcss_invitation_code.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}