package entity;

import java.util.ArrayList;
import java.util.List;

public class SvcssCourseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    public SvcssCourseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCourseIdIsNull() {
            addCriterion("course_id is null");
            return (Criteria) this;
        }

        public Criteria andCourseIdIsNotNull() {
            addCriterion("course_id is not null");
            return (Criteria) this;
        }

        public Criteria andCourseIdEqualTo(String value) {
            addCriterion("course_id =", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotEqualTo(String value) {
            addCriterion("course_id <>", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdGreaterThan(String value) {
            addCriterion("course_id >", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdGreaterThanOrEqualTo(String value) {
            addCriterion("course_id >=", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdLessThan(String value) {
            addCriterion("course_id <", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdLessThanOrEqualTo(String value) {
            addCriterion("course_id <=", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdLike(String value) {
            addCriterion("course_id like", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotLike(String value) {
            addCriterion("course_id not like", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdIn(List<String> values) {
            addCriterion("course_id in", values, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotIn(List<String> values) {
            addCriterion("course_id not in", values, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdBetween(String value1, String value2) {
            addCriterion("course_id between", value1, value2, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotBetween(String value1, String value2) {
            addCriterion("course_id not between", value1, value2, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseCapacityIsNull() {
            addCriterion("course_capacity is null");
            return (Criteria) this;
        }

        public Criteria andCourseCapacityIsNotNull() {
            addCriterion("course_capacity is not null");
            return (Criteria) this;
        }

        public Criteria andCourseCapacityEqualTo(String value) {
            addCriterion("course_capacity =", value, "courseCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseCapacityNotEqualTo(String value) {
            addCriterion("course_capacity <>", value, "courseCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseCapacityGreaterThan(String value) {
            addCriterion("course_capacity >", value, "courseCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseCapacityGreaterThanOrEqualTo(String value) {
            addCriterion("course_capacity >=", value, "courseCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseCapacityLessThan(String value) {
            addCriterion("course_capacity <", value, "courseCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseCapacityLessThanOrEqualTo(String value) {
            addCriterion("course_capacity <=", value, "courseCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseCapacityLike(String value) {
            addCriterion("course_capacity like", value, "courseCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseCapacityNotLike(String value) {
            addCriterion("course_capacity not like", value, "courseCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseCapacityIn(List<String> values) {
            addCriterion("course_capacity in", values, "courseCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseCapacityNotIn(List<String> values) {
            addCriterion("course_capacity not in", values, "courseCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseCapacityBetween(String value1, String value2) {
            addCriterion("course_capacity between", value1, value2, "courseCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseCapacityNotBetween(String value1, String value2) {
            addCriterion("course_capacity not between", value1, value2, "courseCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseResidualCapacityIsNull() {
            addCriterion("\"course_residual capacity\" is null");
            return (Criteria) this;
        }

        public Criteria andCourseResidualCapacityIsNotNull() {
            addCriterion("\"course_residual capacity\" is not null");
            return (Criteria) this;
        }

        public Criteria andCourseResidualCapacityEqualTo(String value) {
            addCriterion("\"course_residual capacity\" =", value, "courseResidualCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseResidualCapacityNotEqualTo(String value) {
            addCriterion("\"course_residual capacity\" <>", value, "courseResidualCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseResidualCapacityGreaterThan(String value) {
            addCriterion("\"course_residual capacity\" >", value, "courseResidualCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseResidualCapacityGreaterThanOrEqualTo(String value) {
            addCriterion("\"course_residual capacity\" >=", value, "courseResidualCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseResidualCapacityLessThan(String value) {
            addCriterion("\"course_residual capacity\" <", value, "courseResidualCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseResidualCapacityLessThanOrEqualTo(String value) {
            addCriterion("\"course_residual capacity\" <=", value, "courseResidualCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseResidualCapacityLike(String value) {
            addCriterion("\"course_residual capacity\" like", value, "courseResidualCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseResidualCapacityNotLike(String value) {
            addCriterion("\"course_residual capacity\" not like", value, "courseResidualCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseResidualCapacityIn(List<String> values) {
            addCriterion("\"course_residual capacity\" in", values, "courseResidualCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseResidualCapacityNotIn(List<String> values) {
            addCriterion("\"course_residual capacity\" not in", values, "courseResidualCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseResidualCapacityBetween(String value1, String value2) {
            addCriterion("\"course_residual capacity\" between", value1, value2, "courseResidualCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseResidualCapacityNotBetween(String value1, String value2) {
            addCriterion("\"course_residual capacity\" not between", value1, value2, "courseResidualCapacity");
            return (Criteria) this;
        }

        public Criteria andCourseSchooltimeIsNull() {
            addCriterion("course_schooltime is null");
            return (Criteria) this;
        }

        public Criteria andCourseSchooltimeIsNotNull() {
            addCriterion("course_schooltime is not null");
            return (Criteria) this;
        }

        public Criteria andCourseSchooltimeEqualTo(String value) {
            addCriterion("course_schooltime =", value, "courseSchooltime");
            return (Criteria) this;
        }

        public Criteria andCourseSchooltimeNotEqualTo(String value) {
            addCriterion("course_schooltime <>", value, "courseSchooltime");
            return (Criteria) this;
        }

        public Criteria andCourseSchooltimeGreaterThan(String value) {
            addCriterion("course_schooltime >", value, "courseSchooltime");
            return (Criteria) this;
        }

        public Criteria andCourseSchooltimeGreaterThanOrEqualTo(String value) {
            addCriterion("course_schooltime >=", value, "courseSchooltime");
            return (Criteria) this;
        }

        public Criteria andCourseSchooltimeLessThan(String value) {
            addCriterion("course_schooltime <", value, "courseSchooltime");
            return (Criteria) this;
        }

        public Criteria andCourseSchooltimeLessThanOrEqualTo(String value) {
            addCriterion("course_schooltime <=", value, "courseSchooltime");
            return (Criteria) this;
        }

        public Criteria andCourseSchooltimeLike(String value) {
            addCriterion("course_schooltime like", value, "courseSchooltime");
            return (Criteria) this;
        }

        public Criteria andCourseSchooltimeNotLike(String value) {
            addCriterion("course_schooltime not like", value, "courseSchooltime");
            return (Criteria) this;
        }

        public Criteria andCourseSchooltimeIn(List<String> values) {
            addCriterion("course_schooltime in", values, "courseSchooltime");
            return (Criteria) this;
        }

        public Criteria andCourseSchooltimeNotIn(List<String> values) {
            addCriterion("course_schooltime not in", values, "courseSchooltime");
            return (Criteria) this;
        }

        public Criteria andCourseSchooltimeBetween(String value1, String value2) {
            addCriterion("course_schooltime between", value1, value2, "courseSchooltime");
            return (Criteria) this;
        }

        public Criteria andCourseSchooltimeNotBetween(String value1, String value2) {
            addCriterion("course_schooltime not between", value1, value2, "courseSchooltime");
            return (Criteria) this;
        }

        public Criteria andCouresClassLocationIsNull() {
            addCriterion("coures_class_location is null");
            return (Criteria) this;
        }

        public Criteria andCouresClassLocationIsNotNull() {
            addCriterion("coures_class_location is not null");
            return (Criteria) this;
        }

        public Criteria andCouresClassLocationEqualTo(String value) {
            addCriterion("coures_class_location =", value, "couresClassLocation");
            return (Criteria) this;
        }

        public Criteria andCouresClassLocationNotEqualTo(String value) {
            addCriterion("coures_class_location <>", value, "couresClassLocation");
            return (Criteria) this;
        }

        public Criteria andCouresClassLocationGreaterThan(String value) {
            addCriterion("coures_class_location >", value, "couresClassLocation");
            return (Criteria) this;
        }

        public Criteria andCouresClassLocationGreaterThanOrEqualTo(String value) {
            addCriterion("coures_class_location >=", value, "couresClassLocation");
            return (Criteria) this;
        }

        public Criteria andCouresClassLocationLessThan(String value) {
            addCriterion("coures_class_location <", value, "couresClassLocation");
            return (Criteria) this;
        }

        public Criteria andCouresClassLocationLessThanOrEqualTo(String value) {
            addCriterion("coures_class_location <=", value, "couresClassLocation");
            return (Criteria) this;
        }

        public Criteria andCouresClassLocationLike(String value) {
            addCriterion("coures_class_location like", value, "couresClassLocation");
            return (Criteria) this;
        }

        public Criteria andCouresClassLocationNotLike(String value) {
            addCriterion("coures_class_location not like", value, "couresClassLocation");
            return (Criteria) this;
        }

        public Criteria andCouresClassLocationIn(List<String> values) {
            addCriterion("coures_class_location in", values, "couresClassLocation");
            return (Criteria) this;
        }

        public Criteria andCouresClassLocationNotIn(List<String> values) {
            addCriterion("coures_class_location not in", values, "couresClassLocation");
            return (Criteria) this;
        }

        public Criteria andCouresClassLocationBetween(String value1, String value2) {
            addCriterion("coures_class_location between", value1, value2, "couresClassLocation");
            return (Criteria) this;
        }

        public Criteria andCouresClassLocationNotBetween(String value1, String value2) {
            addCriterion("coures_class_location not between", value1, value2, "couresClassLocation");
            return (Criteria) this;
        }

        public Criteria andCouresCompanyIdIsNull() {
            addCriterion("coures_company_id is null");
            return (Criteria) this;
        }

        public Criteria andCouresCompanyIdIsNotNull() {
            addCriterion("coures_company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCouresCompanyIdEqualTo(String value) {
            addCriterion("coures_company_id =", value, "couresCompanyId");
            return (Criteria) this;
        }

        public Criteria andCouresCompanyIdNotEqualTo(String value) {
            addCriterion("coures_company_id <>", value, "couresCompanyId");
            return (Criteria) this;
        }

        public Criteria andCouresCompanyIdGreaterThan(String value) {
            addCriterion("coures_company_id >", value, "couresCompanyId");
            return (Criteria) this;
        }

        public Criteria andCouresCompanyIdGreaterThanOrEqualTo(String value) {
            addCriterion("coures_company_id >=", value, "couresCompanyId");
            return (Criteria) this;
        }

        public Criteria andCouresCompanyIdLessThan(String value) {
            addCriterion("coures_company_id <", value, "couresCompanyId");
            return (Criteria) this;
        }

        public Criteria andCouresCompanyIdLessThanOrEqualTo(String value) {
            addCriterion("coures_company_id <=", value, "couresCompanyId");
            return (Criteria) this;
        }

        public Criteria andCouresCompanyIdLike(String value) {
            addCriterion("coures_company_id like", value, "couresCompanyId");
            return (Criteria) this;
        }

        public Criteria andCouresCompanyIdNotLike(String value) {
            addCriterion("coures_company_id not like", value, "couresCompanyId");
            return (Criteria) this;
        }

        public Criteria andCouresCompanyIdIn(List<String> values) {
            addCriterion("coures_company_id in", values, "couresCompanyId");
            return (Criteria) this;
        }

        public Criteria andCouresCompanyIdNotIn(List<String> values) {
            addCriterion("coures_company_id not in", values, "couresCompanyId");
            return (Criteria) this;
        }

        public Criteria andCouresCompanyIdBetween(String value1, String value2) {
            addCriterion("coures_company_id between", value1, value2, "couresCompanyId");
            return (Criteria) this;
        }

        public Criteria andCouresCompanyIdNotBetween(String value1, String value2) {
            addCriterion("coures_company_id not between", value1, value2, "couresCompanyId");
            return (Criteria) this;
        }

        public Criteria andCourseTeacherIdIsNull() {
            addCriterion("course_teacher_id is null");
            return (Criteria) this;
        }

        public Criteria andCourseTeacherIdIsNotNull() {
            addCriterion("course_teacher_id is not null");
            return (Criteria) this;
        }

        public Criteria andCourseTeacherIdEqualTo(String value) {
            addCriterion("course_teacher_id =", value, "courseTeacherId");
            return (Criteria) this;
        }

        public Criteria andCourseTeacherIdNotEqualTo(String value) {
            addCriterion("course_teacher_id <>", value, "courseTeacherId");
            return (Criteria) this;
        }

        public Criteria andCourseTeacherIdGreaterThan(String value) {
            addCriterion("course_teacher_id >", value, "courseTeacherId");
            return (Criteria) this;
        }

        public Criteria andCourseTeacherIdGreaterThanOrEqualTo(String value) {
            addCriterion("course_teacher_id >=", value, "courseTeacherId");
            return (Criteria) this;
        }

        public Criteria andCourseTeacherIdLessThan(String value) {
            addCriterion("course_teacher_id <", value, "courseTeacherId");
            return (Criteria) this;
        }

        public Criteria andCourseTeacherIdLessThanOrEqualTo(String value) {
            addCriterion("course_teacher_id <=", value, "courseTeacherId");
            return (Criteria) this;
        }

        public Criteria andCourseTeacherIdLike(String value) {
            addCriterion("course_teacher_id like", value, "courseTeacherId");
            return (Criteria) this;
        }

        public Criteria andCourseTeacherIdNotLike(String value) {
            addCriterion("course_teacher_id not like", value, "courseTeacherId");
            return (Criteria) this;
        }

        public Criteria andCourseTeacherIdIn(List<String> values) {
            addCriterion("course_teacher_id in", values, "courseTeacherId");
            return (Criteria) this;
        }

        public Criteria andCourseTeacherIdNotIn(List<String> values) {
            addCriterion("course_teacher_id not in", values, "courseTeacherId");
            return (Criteria) this;
        }

        public Criteria andCourseTeacherIdBetween(String value1, String value2) {
            addCriterion("course_teacher_id between", value1, value2, "courseTeacherId");
            return (Criteria) this;
        }

        public Criteria andCourseTeacherIdNotBetween(String value1, String value2) {
            addCriterion("course_teacher_id not between", value1, value2, "courseTeacherId");
            return (Criteria) this;
        }

        public Criteria andCourseStatusIdIsNull() {
            addCriterion("course_status_id is null");
            return (Criteria) this;
        }

        public Criteria andCourseStatusIdIsNotNull() {
            addCriterion("course_status_id is not null");
            return (Criteria) this;
        }

        public Criteria andCourseStatusIdEqualTo(String value) {
            addCriterion("course_status_id =", value, "courseStatusId");
            return (Criteria) this;
        }

        public Criteria andCourseStatusIdNotEqualTo(String value) {
            addCriterion("course_status_id <>", value, "courseStatusId");
            return (Criteria) this;
        }

        public Criteria andCourseStatusIdGreaterThan(String value) {
            addCriterion("course_status_id >", value, "courseStatusId");
            return (Criteria) this;
        }

        public Criteria andCourseStatusIdGreaterThanOrEqualTo(String value) {
            addCriterion("course_status_id >=", value, "courseStatusId");
            return (Criteria) this;
        }

        public Criteria andCourseStatusIdLessThan(String value) {
            addCriterion("course_status_id <", value, "courseStatusId");
            return (Criteria) this;
        }

        public Criteria andCourseStatusIdLessThanOrEqualTo(String value) {
            addCriterion("course_status_id <=", value, "courseStatusId");
            return (Criteria) this;
        }

        public Criteria andCourseStatusIdLike(String value) {
            addCriterion("course_status_id like", value, "courseStatusId");
            return (Criteria) this;
        }

        public Criteria andCourseStatusIdNotLike(String value) {
            addCriterion("course_status_id not like", value, "courseStatusId");
            return (Criteria) this;
        }

        public Criteria andCourseStatusIdIn(List<String> values) {
            addCriterion("course_status_id in", values, "courseStatusId");
            return (Criteria) this;
        }

        public Criteria andCourseStatusIdNotIn(List<String> values) {
            addCriterion("course_status_id not in", values, "courseStatusId");
            return (Criteria) this;
        }

        public Criteria andCourseStatusIdBetween(String value1, String value2) {
            addCriterion("course_status_id between", value1, value2, "courseStatusId");
            return (Criteria) this;
        }

        public Criteria andCourseStatusIdNotBetween(String value1, String value2) {
            addCriterion("course_status_id not between", value1, value2, "courseStatusId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table svcss_course
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}