package entity;

public class SvcssCompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_company.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_company.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_company.company_code
     *
     * @mbg.generated
     */
    private String companyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_company.company_certificate
     *
     * @mbg.generated
     */
    private String companyCertificate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_company.company_audit_manager
     *
     * @mbg.generated
     */
    private String companyAuditManager;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_company.company_id
     *
     * @return the value of svcss_company.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_company.company_id
     *
     * @param companyId the value for svcss_company.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_company.company_name
     *
     * @return the value of svcss_company.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_company.company_name
     *
     * @param companyName the value for svcss_company.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_company.company_code
     *
     * @return the value of svcss_company.company_code
     *
     * @mbg.generated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_company.company_code
     *
     * @param companyCode the value for svcss_company.company_code
     *
     * @mbg.generated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_company.company_certificate
     *
     * @return the value of svcss_company.company_certificate
     *
     * @mbg.generated
     */
    public String getCompanyCertificate() {
        return companyCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_company.company_certificate
     *
     * @param companyCertificate the value for svcss_company.company_certificate
     *
     * @mbg.generated
     */
    public void setCompanyCertificate(String companyCertificate) {
        this.companyCertificate = companyCertificate == null ? null : companyCertificate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_company.company_audit_manager
     *
     * @return the value of svcss_company.company_audit_manager
     *
     * @mbg.generated
     */
    public String getCompanyAuditManager() {
        return companyAuditManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_company.company_audit_manager
     *
     * @param companyAuditManager the value for svcss_company.company_audit_manager
     *
     * @mbg.generated
     */
    public void setCompanyAuditManager(String companyAuditManager) {
        this.companyAuditManager = companyAuditManager == null ? null : companyAuditManager.trim();
    }
}