package entity;

public class SvcssGradeStatistics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_grade_statistics.statistics_id
     *
     * @mbg.generated
     */
    private String statisticsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_grade_statistics.statistics_course_id
     *
     * @mbg.generated
     */
    private String statisticsCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_grade_statistics.statistics_stunum
     *
     * @mbg.generated
     */
    private String statisticsStunum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_grade_statistics.statistics_have_score
     *
     * @mbg.generated
     */
    private String statisticsHaveScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_grade_statistics.statistics_not_score
     *
     * @mbg.generated
     */
    private String statisticsNotScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svcss_grade_statistics.statistics_pass_rate
     *
     * @mbg.generated
     */
    private String statisticsPassRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_grade_statistics.statistics_id
     *
     * @return the value of svcss_grade_statistics.statistics_id
     *
     * @mbg.generated
     */
    public String getStatisticsId() {
        return statisticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_grade_statistics.statistics_id
     *
     * @param statisticsId the value for svcss_grade_statistics.statistics_id
     *
     * @mbg.generated
     */
    public void setStatisticsId(String statisticsId) {
        this.statisticsId = statisticsId == null ? null : statisticsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_grade_statistics.statistics_course_id
     *
     * @return the value of svcss_grade_statistics.statistics_course_id
     *
     * @mbg.generated
     */
    public String getStatisticsCourseId() {
        return statisticsCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_grade_statistics.statistics_course_id
     *
     * @param statisticsCourseId the value for svcss_grade_statistics.statistics_course_id
     *
     * @mbg.generated
     */
    public void setStatisticsCourseId(String statisticsCourseId) {
        this.statisticsCourseId = statisticsCourseId == null ? null : statisticsCourseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_grade_statistics.statistics_stunum
     *
     * @return the value of svcss_grade_statistics.statistics_stunum
     *
     * @mbg.generated
     */
    public String getStatisticsStunum() {
        return statisticsStunum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_grade_statistics.statistics_stunum
     *
     * @param statisticsStunum the value for svcss_grade_statistics.statistics_stunum
     *
     * @mbg.generated
     */
    public void setStatisticsStunum(String statisticsStunum) {
        this.statisticsStunum = statisticsStunum == null ? null : statisticsStunum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_grade_statistics.statistics_have_score
     *
     * @return the value of svcss_grade_statistics.statistics_have_score
     *
     * @mbg.generated
     */
    public String getStatisticsHaveScore() {
        return statisticsHaveScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_grade_statistics.statistics_have_score
     *
     * @param statisticsHaveScore the value for svcss_grade_statistics.statistics_have_score
     *
     * @mbg.generated
     */
    public void setStatisticsHaveScore(String statisticsHaveScore) {
        this.statisticsHaveScore = statisticsHaveScore == null ? null : statisticsHaveScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_grade_statistics.statistics_not_score
     *
     * @return the value of svcss_grade_statistics.statistics_not_score
     *
     * @mbg.generated
     */
    public String getStatisticsNotScore() {
        return statisticsNotScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_grade_statistics.statistics_not_score
     *
     * @param statisticsNotScore the value for svcss_grade_statistics.statistics_not_score
     *
     * @mbg.generated
     */
    public void setStatisticsNotScore(String statisticsNotScore) {
        this.statisticsNotScore = statisticsNotScore == null ? null : statisticsNotScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svcss_grade_statistics.statistics_pass_rate
     *
     * @return the value of svcss_grade_statistics.statistics_pass_rate
     *
     * @mbg.generated
     */
    public String getStatisticsPassRate() {
        return statisticsPassRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svcss_grade_statistics.statistics_pass_rate
     *
     * @param statisticsPassRate the value for svcss_grade_statistics.statistics_pass_rate
     *
     * @mbg.generated
     */
    public void setStatisticsPassRate(String statisticsPassRate) {
        this.statisticsPassRate = statisticsPassRate == null ? null : statisticsPassRate.trim();
    }
}