package mapper;

import entity.SvcssCourseTag;
import entity.SvcssCourseTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SvcssCourseTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course_tag
     *
     * @mbg.generated
     */
    long countByExample(SvcssCourseTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course_tag
     *
     * @mbg.generated
     */
    int deleteByExample(SvcssCourseTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course_tag
     *
     * @mbg.generated
     */
    int insert(SvcssCourseTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course_tag
     *
     * @mbg.generated
     */
    int insertSelective(SvcssCourseTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course_tag
     *
     * @mbg.generated
     */
    List<SvcssCourseTag> selectByExample(SvcssCourseTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course_tag
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SvcssCourseTag record, @Param("example") SvcssCourseTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course_tag
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SvcssCourseTag record, @Param("example") SvcssCourseTagExample example);
}