package mapper;

import entity.SvcssCourse;
import entity.SvcssCourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SvcssCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    long countByExample(SvcssCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    int deleteByExample(SvcssCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    int insert(SvcssCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    int insertSelective(SvcssCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    List<SvcssCourse> selectByExample(SvcssCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SvcssCourse record, @Param("example") SvcssCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SvcssCourse record, @Param("example") SvcssCourseExample example);
}