package mapper;

import entity.SvcssTeacher;
import entity.SvcssTeacherExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SvcssTeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_teacher
     *
     * @mbg.generated
     */
    long countByExample(SvcssTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_teacher
     *
     * @mbg.generated
     */
    int deleteByExample(SvcssTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_teacher
     *
     * @mbg.generated
     */
    int insert(SvcssTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_teacher
     *
     * @mbg.generated
     */
    int insertSelective(SvcssTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_teacher
     *
     * @mbg.generated
     */
    List<SvcssTeacher> selectByExample(SvcssTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_teacher
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SvcssTeacher record, @Param("example") SvcssTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_teacher
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SvcssTeacher record, @Param("example") SvcssTeacherExample example);
}