package mapper;

import entity.SvcssCourseStatus;
import entity.SvcssCourseStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SvcssCourseStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course_status
     *
     * @mbg.generated
     */
    long countByExample(SvcssCourseStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course_status
     *
     * @mbg.generated
     */
    int deleteByExample(SvcssCourseStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course_status
     *
     * @mbg.generated
     */
    int insert(SvcssCourseStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course_status
     *
     * @mbg.generated
     */
    int insertSelective(SvcssCourseStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course_status
     *
     * @mbg.generated
     */
    List<SvcssCourseStatus> selectByExample(SvcssCourseStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course_status
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SvcssCourseStatus record, @Param("example") SvcssCourseStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_course_status
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SvcssCourseStatus record, @Param("example") SvcssCourseStatusExample example);
}