package mapper;

import entity.SvcssGrade;
import entity.SvcssGradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SvcssGradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    long countByExample(SvcssGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    int deleteByExample(SvcssGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    int insert(SvcssGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    int insertSelective(SvcssGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    List<SvcssGrade> selectByExample(SvcssGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SvcssGrade record, @Param("example") SvcssGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SvcssGrade record, @Param("example") SvcssGradeExample example);
}