package mapper;

import entity.SvcssStudent;
import entity.SvcssStudentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SvcssStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_student
     *
     * @mbg.generated
     */
    long countByExample(SvcssStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_student
     *
     * @mbg.generated
     */
    int deleteByExample(SvcssStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_student
     *
     * @mbg.generated
     */
    int insert(SvcssStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_student
     *
     * @mbg.generated
     */
    int insertSelective(SvcssStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_student
     *
     * @mbg.generated
     */
    List<SvcssStudent> selectByExample(SvcssStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_student
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SvcssStudent record, @Param("example") SvcssStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_student
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SvcssStudent record, @Param("example") SvcssStudentExample example);
}