package mapper;

import entity.SvcssManager;
import entity.SvcssManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SvcssManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_manager
     *
     * @mbg.generated
     */
    long countByExample(SvcssManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_manager
     *
     * @mbg.generated
     */
    int deleteByExample(SvcssManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_manager
     *
     * @mbg.generated
     */
    int insert(SvcssManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_manager
     *
     * @mbg.generated
     */
    int insertSelective(SvcssManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_manager
     *
     * @mbg.generated
     */
    List<SvcssManager> selectByExample(SvcssManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_manager
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SvcssManager record, @Param("example") SvcssManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_manager
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SvcssManager record, @Param("example") SvcssManagerExample example);
}