package mapper;

import entity.SvcssCompany;
import entity.SvcssCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SvcssCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_company
     *
     * @mbg.generated
     */
    long countByExample(SvcssCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_company
     *
     * @mbg.generated
     */
    int deleteByExample(SvcssCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_company
     *
     * @mbg.generated
     */
    int insert(SvcssCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_company
     *
     * @mbg.generated
     */
    int insertSelective(SvcssCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_company
     *
     * @mbg.generated
     */
    List<SvcssCompany> selectByExample(SvcssCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_company
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SvcssCompany record, @Param("example") SvcssCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_company
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SvcssCompany record, @Param("example") SvcssCompanyExample example);
}