package mapper;

import entity.SvcssGradeStatistics;
import entity.SvcssGradeStatisticsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SvcssGradeStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade_statistics
     *
     * @mbg.generated
     */
    long countByExample(SvcssGradeStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade_statistics
     *
     * @mbg.generated
     */
    int deleteByExample(SvcssGradeStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade_statistics
     *
     * @mbg.generated
     */
    int insert(SvcssGradeStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade_statistics
     *
     * @mbg.generated
     */
    int insertSelective(SvcssGradeStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade_statistics
     *
     * @mbg.generated
     */
    List<SvcssGradeStatistics> selectByExample(SvcssGradeStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade_statistics
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SvcssGradeStatistics record, @Param("example") SvcssGradeStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svcss_grade_statistics
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SvcssGradeStatistics record, @Param("example") SvcssGradeStatisticsExample example);
}